# Note: Local Grantmakers.io development requires a _config_development.yml with local Algolia API keys
# bundle exec jekyll serve --livereload --config _config.yml

# Site settings
# Meta tags
title: climind.cn
description: Quickly find climate datasets from 109,000 sources in the world. 
languages: ["en", "cn"]

# Jekyll settings
baseurl: # Leave this blank unless your site is located on a subpath, e.g. /blog
url: https://www.climind.cn
sass:
  sass_dir: assets/css/_sass
plugins:
  - jekyll-redirect-from

# Google Analytics
google_analytics: G-RV3RW7CWQB

number_of_searchable_records: 57
# searchable grants figure pulled directly from Algolia

# Build settings
markdown: kramdown
kramdown:
  input: GFM
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - node_modules
  - package-lock.json
  - package.json
  - scripts/
  - data/ #Note: does not affect _data folder
  - vendor/

webrick:
  headers:
    Access-Control-Allow-Origin: "*"