title: Climind Database for NbS
description: Search-oriented Database for Nature-based Solutions
theme: just-the-docs
logo: "/assets/logo.jpg"
# color_scheme: dark

url: https://climind.github.io/soda

# Aux links for the upper right navigation
aux_links:
  Visit Climind: https://climind.co
# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

liquid:
  error_mode: warn